extends Node

signal weapon_swap
signal player_take_damage
signal player_increase_health
signal player_increase_shield
signal player_death
signal upgrade_spear
signal upgrade_sword
signal upgrade_axe
signal upgrade_health
signal exp_add
signal exp_sub
signal player_restart
